-keep class ai.onnxruntime.** { *; }
-keep class io.github.capsopasme.mossnano.engine.SpmTokenizer { native <methods>; *; }
-keep class io.github.capsopasme.mossnano.engine.CpuAffinity { native <methods>; }
